services:
  db:
    container_name: shootingclub-db
    build:
      context: ./db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "${DB_PASSWORD}",
          "-Q",
          "SELECT 1",
        ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  backend:
    container_name: shootingclub-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Connection=Server=db;Database=ShootingClubDB;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
    restart: on-failure

  nginx:
    container_name: shootingclub-proxy
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

volumes:
  db-data:
